version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: game_server
    networks:
      servers:
        ipv4_address: 10.0.11.1
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    container_name: server_redis
    networks:
      servers:
        ipv4_address: 10.0.11.2
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  servers:
    external: true
    name: servers

volumes:
  redis_data: 