version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: server/server.Dockerfile
    cap_add:
      - NET_ADMIN
    networks:
      - servers
      - localnet
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    networks:
      - localnet
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  servers:
    external: true
    name: servers
  localnet:
    driver: bridge

volumes:
  redis_data: 